// src/services/api.js
// ─────────────────────────────────────────────────────────
// All Supabase CRUD operations organized by domain.
// Import into components: import { registrations, matches } from '@/services/api'
// ─────────────────────────────────────────────────────────

import { supabase } from "../supabaseClient";

// ═══════════════════════════════════════════════════════════
// EVENTS
// ═══════════════════════════════════════════════════════════

export const events = {
  async get(eventId) {
    const { data, error } = await supabase
      .from("events")
      .select("*, organizations(*), event_dates(*)")
      .eq("id", eventId)
      .maybeSingle();
    if (error) throw error;
    return data;
  },

  async getByOrg(orgId) {
    const { data, error } = await supabase
      .from("events")
      .select("*")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async update(eventId, updates) {
    const { data, error } = await supabase
      .from("events")
      .update(updates)
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateFundraising(eventId, amount) {
    const { data, error } = await supabase
      .from("events")
      .update({ fundraising_current: amount })
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateRules(eventId, rulesContent) {
    const { data, error } = await supabase
      .from("events")
      .update({ rules_content: rulesContent })
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateStatus(eventId, status) {
    const updates = { status };
    if (status === "registration_open") updates.published_at = new Date().toISOString();
    const { data, error } = await supabase
      .from("events")
      .update(updates)
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// REGISTRATIONS
// ═══════════════════════════════════════════════════════════

export const registrations = {
  // Public: submit a new registration
  async create(eventId, formData) {
    const { data: event } = await supabase
      .from("events")
      .select("entry_fee, recon_prefix, recon_counter")
      .eq("id", eventId)
      .single();

    const { data, error } = await supabase
      .from("registrations")
      .insert({
        event_id: eventId,
        team_name: formData.teamName,
        team_slogan: formData.slogan || null,
        captain_name: formData.captainName,
        captain_email: formData.captainEmail,
        captain_phone: formData.captainPhone,
        captain_shirt: formData.captainShirt || null,
        captain_dietary: formData.captainDiet || null,
        payment_method: formData.paymentMethod,
        fee_amount: event.entry_fee,
        donation_amount: formData.donation || 0,
        total_amount: event.entry_fee + (formData.donation || 0),
        image_consent: formData.imageConsent || false,
        waiver_accepted: formData.waiverAccepted || false,
        team_story: formData.story || null,
        // reconciliation_code auto-generated by trigger
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: list all registrations for an event
  async list(eventId, filters = {}) {
    let query = supabase
      .from("registrations")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });

    if (filters.paymentStatus) query = query.eq("payment_status", filters.paymentStatus);
    if (filters.status) query = query.eq("status", filters.status);
    if (filters.search) {
      query = query.or(
        `team_name.ilike.%${filters.search}%,captain_name.ilike.%${filters.search}%,reconciliation_code.ilike.%${filters.search}%`
      );
    }

    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Admin: batch update registrations (payment confirmations, rejections)
  async batchUpdate(updates) {
    // updates = [{ id, payment_status, status, payment_confirmed_by, ... }]
    const promises = updates.map(({ id, ...fields }) =>
      supabase.from("registrations").update(fields).eq("id", id)
    );
    const results = await Promise.all(promises);
    const errors = results.filter((r) => r.error);
    if (errors.length) throw new Error(`${errors.length} updates failed`);
    return results.map((r) => r.data);
  },

  // Toggle payment status independently (checkbox-driven)
  async setPaymentReceived(id, received, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        payment_status: received ? "paid" : "pending",
        payment_confirmed_at: received ? new Date().toISOString() : null,
        payment_confirmed_by: received ? adminUserId : null,
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Toggle registration approval independently (checkbox-driven)
  async setApproved(id, approved, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        status: approved ? "approved" : "submitted",
        confirmed_at: approved ? new Date().toISOString() : null,
        approved_by: approved ? adminUserId : null,
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: confirm a single payment
  async confirmPayment(id, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        payment_status: "paid",
        status: "confirmed",
        payment_confirmed_at: new Date().toISOString(),
        payment_confirmed_by: adminUserId,
        confirmed_at: new Date().toISOString(),
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: reject registration
  async reject(id) {
    const { data, error } = await supabase
      .from("registrations")
      .update({ status: "rejected" })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// TEAMS
// ═══════════════════════════════════════════════════════════

export const teams = {
  // Create team at registration-submission time (not post-approval —
  // see FEATURE_SPEC_team_roster_registration.md). Replaces the old,
  // never-wired createFromRegistration().
  async create(eventId, registrationId, { name, slogan, logoUrl } = {}) {
    const { data, error } = await supabase
      .from("teams")
      .insert({
        event_id: eventId,
        registration_id: registrationId,
        name,
        slogan: slogan || null,
        logo_url: logoUrl || null,
        status: "pending",
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async list(eventId) {
    const { data, error } = await supabase
      .from("teams")
      .select("*, players(*), pool:pools(name)")
      .eq("event_id", eventId)
      .order("name");
    if (error) throw error;
    return data;
  },

  // Phase 6: routed through a SECURITY DEFINER RPC (migration 019) rather
  // than a raw .update() — referee/control_desk no longer have a blanket
  // teams UPDATE grant, only this narrow, explicitly-columned action.
  // checked_in_by is now set server-side from auth.uid() rather than a
  // client-passed id (the previous adminUserId param was never actually
  // passed by any call site, so checked_in_by was always null in practice).
  async checkIn(teamId) {
    const { error } = await supabase.rpc("team_set_checked_in", { p_team_id: teamId, p_checked_in: true });
    if (error) throw error;
  },

  async undoCheckIn(teamId) {
    const { error } = await supabase.rpc("team_set_checked_in", { p_team_id: teamId, p_checked_in: false });
    if (error) throw error;
  },

  async assignPool(teamId, poolId) {
    const { data, error } = await supabase
      .from("teams")
      .update({ pool_id: poolId })
      .eq("id", teamId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Phase 6: routed through a SECURITY DEFINER RPC (migration 019) — see checkIn().
  async markEliminated(teamId, finalRank) {
    const { error } = await supabase.rpc("team_mark_eliminated", { p_team_id: teamId, p_final_rank: finalRank });
    if (error) throw error;
  },
};

// ═══════════════════════════════════════════════════════════
// PLAYERS
// ═══════════════════════════════════════════════════════════

export const players = {
  async createBatch(teamId, eventId, registrationId, playerList) {
    // playerList = [{ name, email, phone, is_captain, is_coach, shirt_size, dietary_needs }]
    // in final roster order — sort_order is derived from array position
    // (0 = captain), per players.sort_order's existing convention.
    const rows = playerList.map((p, i) => ({
      team_id: teamId,
      event_id: eventId,
      registration_id: registrationId,
      full_name: p.name,
      email: p.email || null,
      phone: p.phone || null,
      is_captain: p.is_captain || false,
      is_coach: p.is_coach || false,
      shirt_size: p.shirt_size || null,
      dietary_needs: p.dietary_needs || null,
      sort_order: i,
      status: "pending",
      self_registered: false,
    }));
    const { data, error } = await supabase.from("players").insert(rows).select();
    if (error) throw error;
    return data;
  },

  // Admin: batch update players (per-player approve/reject) — mirrors
  // registrations.batchUpdate's shape/pattern. Each status write here
  // fires the recompute_team_status() trigger (migration 016), which
  // keeps teams.status in sync — nothing on the client needs to
  // recompute team status itself.
  async batchUpdate(updates) {
    // updates = [{ id, status }]
    const promises = updates.map(({ id, ...fields }) =>
      supabase.from("players").update(fields).eq("id", id)
    );
    const results = await Promise.all(promises);
    const errors = results.filter((r) => r.error);
    if (errors.length) throw new Error(`${errors.length} updates failed`);
    return results.map((r) => r.data);
  },

  async getByPhone(eventId, phone) {
    const { data, error } = await supabase
      .from("players")
      .select("*, team:teams(*)")
      .eq("event_id", eventId)
      .eq("phone", phone)
      .eq("is_captain", true)
      .single();
    if (error) throw error;
    return data;
  },

  // ── QR/magic-link check-in (FEATURE_SPEC_entitlements_and_identity.md Phase 3) ──

  // Reads the authenticated captain's own row via self-scoped RLS
  // (migration 012) — no explicit id needed, RLS scopes to
  // auth_user_id = auth.uid(). Only works after linkAuthOnCheckin() has run.
  async getSelfForCheckin() {
    const { data, error } = await supabase
      .from("players")
      .select("*, team:teams(name), event:events(name)")
      .single();
    if (error) throw error;
    return data;
  },

  // Phase 3b: full session payload for CaptainDashboard, used both right
  // after check-in confirm and on a later PlayerPortal.jsx page load with
  // an already-linked session. Roster comes from the public players_public
  // view (id/team_id/is_captain/full_name only — migration 014) since a
  // captain has no RLS grant to read teammates' phone/email/shirt/dietary
  // via the base players table; shirt/dietary are left blank here, same
  // known gap the pre-Phase-2 otp.verify() flow had.
  async getCaptainSessionData() {
    const { data: self, error } = await supabase
      .from("players")
      .select("id, full_name, phone, team:teams(id, name, slogan, seed, checked_in, pool:pools(name))")
      .single();
    if (error) throw error;

    const { data: roster, error: rosterError } = await supabase
      .from("players_public")
      .select("id, team_id, is_captain, full_name")
      .eq("team_id", self.team.id);
    if (rosterError) throw rosterError;

    return {
      name: self.full_name,
      phone: self.phone,
      playerId: self.id,
      team: {
        id: self.team.id,
        name: self.team.name,
        slogan: self.team.slogan || "",
        pool: self.team.pool?.name || "",
        seed: self.team.seed || 0,
        checkedIn: self.team.checked_in || false,
      },
      roster: (roster || []).map((p) => ({
        name: p.full_name,
        role: p.is_captain ? "Captain" : "Player",
        shirt: "",
        dietary: "None",
      })),
    };
  },

  // First-time auth_user_id link — SECURITY DEFINER RPC (migration 018).
  // The self-scoped UPDATE policy can't apply until this has run once,
  // since auth_user_id starts NULL.
  async linkAuthOnCheckin(playerId) {
    const { error } = await supabase.rpc("link_player_auth_on_checkin", { player_id: playerId });
    if (error) throw error;
  },

  async setCheckedIn(playerId) {
    const { data, error } = await supabase
      .from("players")
      .update({ checked_in: true })
      .eq("id", playerId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Phase 6: routed through a SECURITY DEFINER RPC (migration 019),
  // replacing the two raw .update() calls this had in Phase 4 — those
  // relied on the blanket "Admin full players" policy, which no longer
  // grants treasurer/volunteer_coord access, and never granted
  // referee/control_desk anything beyond what "any event-scoped admin"
  // meant at the time. The RPC does both updates atomically and checks
  // admin/referee/control_desk for the team's event internally.
  async transferCaptaincy(teamId, outgoingPlayerId, incomingPlayerId) {
    const { error } = await supabase.rpc("transfer_captaincy", {
      p_team_id: teamId,
      p_outgoing_player_id: outgoingPlayerId,
      p_incoming_player_id: incomingPlayerId,
    });
    if (error) throw error;
  },

  // Calls generate-login-qr Netlify function. Staffed-only as of Phase 3b
  // — accessToken (an admin/referee/control_desk/org_admin/super_admin
  // session token) is required; there is no unauthenticated call path.
  async generateLoginQR(playerId, accessToken) {
    const response = await fetch("/.netlify/functions/generate-login-qr", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
      },
      body: JSON.stringify({ player_id: playerId }),
    });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error || "Failed to generate check-in link");
    return result; // { action_link }
  },
};

// ═══════════════════════════════════════════════════════════
// MATCHES
// ═══════════════════════════════════════════════════════════

export const matches = {
  async list(eventId, filters = {}) {
    let query = supabase
      .from("matches")
      .select(
        "*, team_a:teams!matches_team_a_id_fkey(id, name), team_b:teams!matches_team_b_id_fkey(id, name), playing_area:playing_areas(number, name), pool:pools(name), bracket:brackets(name)"
      )
      .eq("event_id", eventId)
      .order("round")
      .order("match_number");

    if (filters.status) query = query.eq("status", filters.status);
    if (filters.poolId) query = query.eq("pool_id", filters.poolId);
    if (filters.bracketId) query = query.eq("bracket_id", filters.bracketId);

    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  async getLive(eventId) {
    const { data, error } = await supabase
      .from("matches")
      .select(
        "*, team_a:teams!matches_team_a_id_fkey(id, name), team_b:teams!matches_team_b_id_fkey(id, name), playing_area:playing_areas(number, name)"
      )
      .eq("event_id", eventId)
      .in("status", ["live", "score_entered", "disputed"])
      .order("playing_area_id");
    if (error) throw error;
    return data;
  },

  // Captain: submit score (home captain only)
  async submitScore(matchId, teamAScore, teamBScore, captainPhone) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        team_a_score: teamAScore,
        team_b_score: teamBScore,
        score_entered_at: new Date().toISOString(),
        score_entered_by: captainPhone,
        status: "score_entered",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Captain: verify score (away captain)
  async verifyScore(matchId) {
    const { data: match } = await supabase
      .from("matches")
      .select("team_a_score, team_b_score, team_a_id, team_b_id")
      .eq("id", matchId)
      .single();

    const winnerId =
      match.team_a_score > match.team_b_score ? match.team_a_id : match.team_b_id;
    const loserId =
      match.team_a_score > match.team_b_score ? match.team_b_id : match.team_a_id;

    const { data, error } = await supabase
      .from("matches")
      .update({
        score_verified: true,
        score_verified_at: new Date().toISOString(),
        winner_id: winnerId,
        loser_id: loserId,
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Captain: dispute score
  async disputeScore(matchId, reason) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        score_disputed: true,
        dispute_reason: reason,
        status: "disputed",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin/Referee: resolve dispute
  async resolveDispute(matchId, finalScoreA, finalScoreB, resolvedBy) {
    const { data: match } = await supabase
      .from("matches")
      .select("team_a_id, team_b_id")
      .eq("id", matchId)
      .single();

    const winnerId =
      finalScoreA > finalScoreB ? match.team_a_id : match.team_b_id;
    const loserId =
      finalScoreA > finalScoreB ? match.team_b_id : match.team_a_id;

    const { data, error } = await supabase
      .from("matches")
      .update({
        team_a_score: finalScoreA,
        team_b_score: finalScoreB,
        winner_id: winnerId,
        loser_id: loserId,
        score_verified: true,
        score_disputed: false,
        dispute_resolved_by: resolvedBy,
        dispute_resolved_at: new Date().toISOString(),
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: force verify (skip away captain confirmation)
  async forceVerify(matchId, adminUserId) {
    return this.resolveDispute(
      matchId,
      null, // keep existing scores
      null,
      adminUserId
    );
  },

  // Admin: assign to playing area
  async assignArea(matchId, playingAreaId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        playing_area_id: playingAreaId,
        status: "ready",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: start match
  async startMatch(matchId) {
    // Randomize home captain
    await supabase.rpc("assign_home_captain", { match_uuid: matchId });
    const { data, error } = await supabase
      .from("matches")
      .update({
        status: "live",
        started_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: award bye (no-show opponent)
  async awardBye(matchId, winnerTeamId, loserTeamId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        winner_id: winnerTeamId,
        loser_id: loserTeamId,
        team_a_score: 0,
        team_b_score: 0,
        score_verified: true,
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: reassign home captain
  async reassignHomeCaptain(matchId, newHomeCaptainTeamId, newAwayCaptainTeamId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        home_captain_team_id: newHomeCaptainTeamId,
        away_captain_team_id: newAwayCaptainTeamId,
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// POOLS & STANDINGS
// ═══════════════════════════════════════════════════════════

export const pools = {
  async create(eventId, poolNames) {
    const rows = poolNames.map((name, i) => ({
      event_id: eventId,
      name,
      sort_order: i,
    }));
    const { data, error } = await supabase.from("pools").insert(rows).select();
    if (error) throw error;
    return data;
  },

  async listWithStandings(eventId) {
    const { data, error } = await supabase
      .from("pools")
      .select("*, pool_standings(*, team:teams(id, name, slogan))")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    // Sort standings by rank within each pool
    return data.map((pool) => ({
      ...pool,
      pool_standings: pool.pool_standings.sort((a, b) => (a.pool_rank || 99) - (b.pool_rank || 99)),
    }));
  },
};

// ═══════════════════════════════════════════════════════════
// PLAYING AREAS
// ═══════════════════════════════════════════════════════════

export const playingAreas = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("playing_areas")
      .select("*")
      .eq("event_id", eventId)
      .order("number");
    if (error) throw error;
    return data;
  },

  async updateStatus(areaId, status) {
    const { data, error } = await supabase
      .from("playing_areas")
      .update({ status })
      .eq("id", areaId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async createBatch(eventId, count, label = "Court") {
    const rows = Array.from({ length: count }, (_, i) => ({
      event_id: eventId,
      number: i + 1,
      name: `${label} ${i + 1}`,
      status: "available",
    }));
    const { data, error } = await supabase.from("playing_areas").insert(rows).select();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// BRACKETS
// ═══════════════════════════════════════════════════════════

export const brackets = {
  async create(eventId, name, bracketType, format) {
    const { data, error } = await supabase
      .from("brackets")
      .insert({ event_id: eventId, name, bracket_type: bracketType, format })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async listWithMatches(eventId) {
    const { data, error } = await supabase
      .from("brackets")
      .select("*, matches(*, team_a:teams!matches_team_a_id_fkey(name), team_b:teams!matches_team_b_id_fkey(name))")
      .eq("event_id", eventId);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// VOLUNTEERS
// ═══════════════════════════════════════════════════════════

export const volunteers = {
  // Public: submit application
  async apply(eventId, formData) {
    const { data, error } = await supabase
      .from("volunteer_applications")
      .insert({
        event_id: eventId,
        primary_role_id: formData.primaryRoleId,
        other_role_ids: formData.otherRoleIds || [],
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.phone || null,
        experience: formData.experience || null,
        certifications: formData.certifications || null,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: list applications
  async list(eventId, filters = {}) {
    let query = supabase
      .from("volunteer_applications")
      .select("*, primary_role:volunteer_roles!volunteer_applications_primary_role_id_fkey(title)")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (filters.status) query = query.eq("status", filters.status);
    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Admin: batch approve/decline
  async batchUpdate(updates) {
    const promises = updates.map(({ id, status, assignedRoleId, approvedBy }) =>
      supabase.from("volunteer_applications").update({
        status,
        assigned_role_id: assignedRoleId || null,
        approved_by: approvedBy || null,
        approved_at: status === "approved" ? new Date().toISOString() : null,
      }).eq("id", id)
    );
    const results = await Promise.all(promises);
    const errors = results.filter((r) => r.error);
    if (errors.length) throw new Error(`${errors.length} updates failed`);
    return results;
  },

  // Roles
  async listRoles(eventId) {
    const { data, error } = await supabase
      .from("volunteer_roles")
      .select("*")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },

  // ── Volunteer self-service portal (FEATURE_SPEC_entitlements_and_identity.md Phase 5) ──

  // Sends a real magic-link email via Supabase's native passwordless auth.
  // auth_user_id linking happens automatically afterward via migration
  // 013's link_volunteer_auth_by_email() trigger (email-match, SECURITY
  // DEFINER, fires on the resulting auth.users insert/lookup) — no client
  // action needed, unlike the captain QR flow's manual linking RPC.
  async requestLogin(email, eventId) {
    const { error } = await supabase.auth.signInWithOtp({
      email,
      options: { emailRedirectTo: `${window.location.origin}/e/${eventId}/volunteer` },
    });
    if (error) throw error;
  },

  // Reads the authenticated volunteer's own row via self-scoped RLS
  // (migration 013) — no explicit id needed, RLS scopes to
  // auth_user_id = auth.uid(). Only returns a row once the email-match
  // trigger has linked it (i.e. after the first successful magic-link
  // sign-in for this address).
  async getSelf() {
    const { data, error } = await supabase
      .from("volunteer_applications")
      .select("*, primary_role:volunteer_roles!volunteer_applications_primary_role_id_fkey(title), assigned_role:volunteer_roles!volunteer_applications_assigned_role_id_fkey(title)")
      .single();
    if (error) throw error;
    return data;
  },

  // Phase 6: routed through a SECURITY DEFINER RPC (migration 019),
  // replacing a blanket-RLS-backed .update() — see that migration's Part E
  // for why (the old "Self update own volunteer application" policy had
  // no column restriction; a volunteer's own session could otherwise set
  // status directly). The RPC sets all three fields every call, so pass
  // through the current value for any field the caller isn't editing
  // (VolunteerPortal.jsx does this for certifications, which it has no
  // input for) — the RPC has no partial-update concept the way the old
  // .update(allowed) call did.
  async updateSelf(id, fields) {
    const { error } = await supabase.rpc("update_own_volunteer_info", {
      app_id: id,
      p_phone: fields.phone ?? null,
      p_experience: fields.experience ?? null,
      p_certifications: fields.certifications ?? null,
    });
    if (error) throw error;
  },

  async withdraw(id) {
    const { error } = await supabase.rpc("withdraw_own_volunteer_application", { app_id: id });
    if (error) throw error;
  },
};

// ═══════════════════════════════════════════════════════════
// SPONSORS
// ═══════════════════════════════════════════════════════════

export const sponsors = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("sponsors")
      .select("*, tier:sponsor_tiers(name, amount, sort_order)")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },

  async listTiers(eventId) {
    const { data, error } = await supabase
      .from("sponsor_tiers")
      .select("*, sponsors(*)")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },

  async create(eventId, sponsorData) {
    const { data, error } = await supabase
      .from("sponsors")
      .insert({ event_id: eventId, ...sponsorData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async update(id, updates) {
    const { data, error } = await supabase
      .from("sponsors")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// BENEFICIARIES (org-scoped — a beneficiary belongs to the org
// that vouches for it, reusable across that org's events)
// ═══════════════════════════════════════════════════════════

export const beneficiaries = {
  async listByOrg(orgId) {
    const { data, error } = await supabase
      .from("beneficiaries")
      .select("*")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(orgId, beneficiaryData) {
    const { data, error } = await supabase
      .from("beneficiaries")
      .insert({ org_id: orgId, ...beneficiaryData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async update(id, updates) {
    const { data, error } = await supabase
      .from("beneficiaries")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// EVENT BENEFICIARY COMMITMENTS
// ═══════════════════════════════════════════════════════════

export const commitments = {
  async listByEvent(eventId) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .select("*, beneficiary:beneficiaries(*)")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // Used by the publish-flow gate — a charity event needs at least one
  // published commitment before it can go live.
  async getPublished(eventId) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .select("*, beneficiary:beneficiaries(*)")
      .eq("event_id", eventId)
      .eq("status", "published")
      .maybeSingle();
    if (error) throw error;
    return data;
  },

  async create(eventId, commitmentData) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .insert({ event_id: eventId, ...commitmentData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async update(id, updates) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Post-event fulfillment evidence (spec §4). Private bucket (migration
  // 023) — `url` in the returned {url, filename, uploaded_at} entries is
  // a bucket-relative path, NOT a public URL. Call getEvidenceSignedUrl()
  // to get something displayable.
  async uploadEvidenceFile(eventId, file) {
    const path = `${eventId}/${Date.now()}-${file.name}`;
    const { error } = await supabase.storage.from("beneficiary-evidence").upload(path, file);
    if (error) throw error;
    return { url: path, filename: file.name, uploaded_at: new Date().toISOString() };
  },

  async getEvidenceSignedUrl(path) {
    const { data, error } = await supabase.storage.from("beneficiary-evidence").createSignedUrl(path, 3600);
    if (error) throw error;
    return data.signedUrl;
  },

  // Org-side submission — sets fulfillment_status: 'submitted'.
  async submitEvidence(id, { evidenceFiles, evidenceDescription }) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .update({
        fulfillment_status: "submitted",
        evidence_submitted_at: new Date().toISOString(),
        evidence_files: evidenceFiles,
        evidence_description: evidenceDescription,
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // super_admin review — confirmed or disputed.
  async reviewEvidence(id, fulfillmentStatus, reviewedBy) {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .update({
        fulfillment_status: fulfillmentStatus,
        reviewed_by: reviewedBy,
        reviewed_at: new Date().toISOString(),
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // super_admin queue — every commitment awaiting evidence review, across
  // all orgs/events. RLS covers this (is_event_admin_for's first branch
  // is is_super_admin(), so no org/event filter is needed here).
  async listSubmittedForReview() {
    const { data, error } = await supabase
      .from("event_beneficiary_commitments")
      .select("*, beneficiary:beneficiaries(*), event:events(name, org_id, organizations(name))")
      .eq("fulfillment_status", "submitted")
      .order("evidence_submitted_at", { ascending: true });
    if (error) throw error;
    return data;
  },

  // Public-safe read (anon or authenticated) — migration 022's
  // beneficiary_commitments_public view, published commitments only,
  // beneficiary_name + commitment_text only. Used by
  // BeneficiaryCommitmentNotice on the four public/registration surfaces.
  async getPublicNotice(eventId) {
    if (!eventId) return null;
    const { data, error } = await supabase
      .from("beneficiary_commitments_public")
      .select("beneficiary_name, commitment_text")
      .eq("event_id", eventId)
      .maybeSingle();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// LEDGER (bookkeeping only — no payment routing)
// ═══════════════════════════════════════════════════════════

export const expenses = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("expenses")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(eventId, expenseData) {
    const { data, error } = await supabase
      .from("expenses")
      .insert({ event_id: eventId, ...expenseData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async update(id, updates) {
    const { data, error } = await supabase
      .from("expenses")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async remove(id) {
    const { error } = await supabase.from("expenses").delete().eq("id", id);
    if (error) throw error;
  },
};

export const fanDonations = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("fan_donations")
      .select("*, team:teams(name)")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(eventId, donationData) {
    const { data, error } = await supabase
      .from("fan_donations")
      .insert({ event_id: eventId, ...donationData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

export const transactions = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("transactions")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(eventId, orgId, transactionData) {
    const { data, error } = await supabase
      .from("transactions")
      .insert({ event_id: eventId, org_id: orgId, ...transactionData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ARTIFACTS
// ═══════════════════════════════════════════════════════════

export const artifacts = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("artifacts")
      .select("*")
      .eq("event_id", eventId)
      .order("artifact_type");
    if (error) throw error;
    return data;
  },

  async updateStatus(id, status, userId) {
    const updates = { status };
    if (status === "review") {
      updates.reviewed_by = userId;
      updates.reviewed_at = new Date().toISOString();
    } else if (status === "approved") {
      updates.approved_by = userId;
      updates.approved_at = new Date().toISOString();
    } else if (status === "published") {
      updates.published_by = userId;
      updates.published_at = new Date().toISOString();
    }
    const { data, error } = await supabase
      .from("artifacts")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateContent(id, content) {
    const { data, error } = await supabase
      .from("artifacts")
      .update({ content, version: supabase.rpc("increment_version", { artifact_id: id }) })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ANNOUNCEMENTS
// ═══════════════════════════════════════════════════════════

export const announcements = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("announcements")
      .select("*")
      .eq("event_id", eventId)
      .eq("active", true)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(eventId, message, options = {}) {
    const { data, error } = await supabase
      .from("announcements")
      .insert({
        event_id: eventId,
        message,
        priority: options.priority || "normal",
        show_on_tv: options.showOnTV !== false,
        created_by: options.createdBy || null,
        expires_at: options.expiresAt || null,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async deactivate(id) {
    const { data, error } = await supabase
      .from("announcements")
      .update({ active: false })
      .eq("id", id);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ACTIVITY LOG
// ═══════════════════════════════════════════════════════════

export const activityLog = {
  async log(eventId, action, entityType, entityId, details = {}, userId = null) {
    const { error } = await supabase.from("activity_log").insert({
      event_id: eventId,
      user_id: userId,
      action,
      entity_type: entityType,
      entity_id: String(entityId),
      details,
    });
    if (error) console.error("Activity log failed:", error);
  },

  async list(eventId, limit = 50) {
    const { data, error } = await supabase
      .from("activity_log")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false })
      .limit(limit);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// GIFT BASKET & LOCAL SERVICES
// ═══════════════════════════════════════════════════════════

export const giftBasket = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("gift_basket_items")
      .select("*")
      .eq("event_id", eventId)
      .eq("active", true)
      .order("sort_order");
    if (error) throw error;
    return data;
  },
};

export const localServices = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("local_services")
      .select("*")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ADMIN / AUTH
// ═══════════════════════════════════════════════════════════

export const admin = {
  // Get the admin_users row for the currently logged-in user
  async getCurrentAdmin() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;
    const { data, error } = await supabase
      .from("admin_users")
      .select("*, organizations(name), events(name)")
      .eq("id", user.id)
      .single();
    if (error) {
      // No matching admin_users row (e.g. invite wasn't processed yet, or not an admin)
      console.error("getCurrentAdmin failed:", error);
      return null;
    }
    return data;
  },

  // Create an invite (org_admin or super_admin)
  async createInvite(email, role, { orgId = null, eventId = null, displayName = null, invitedBy } = {}) {
    const { data, error } = await supabase
      .from("invites")
      .insert({
        email,
        role,
        org_id: orgId,
        event_id: eventId,
        display_name: displayName,
        invited_by: invitedBy,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // List pending (unused) invites, optionally scoped to an org
  async listInvites(orgId = null) {
    let query = supabase
      .from("invites")
      .select("*")
      .is("used_at", null)
      .gt("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false });
    if (orgId) query = query.eq("org_id", orgId);
    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Fetch an invite by token (for the Accept Invite page, pre-signup)
  async getInviteByToken(token) {
    const { data, error } = await supabase
      .from("invites")
      .select("*, organizations(name)")
      .eq("token", token)
      .is("used_at", null)
      .gt("expires_at", new Date().toISOString())
      .single();
    if (error) throw error;
    return data;
  },

  // List admin_users for an org (Team panel)
  async listOrgAdmins(orgId) {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // List the team relevant to one event: this org's org-level admins
  // (event_id NULL) plus admins scoped to this specific event.
  async listEventTeam(orgId, eventId) {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*")
      .eq("org_id", orgId)
      .or(`event_id.eq.${eventId},event_id.is.null`)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // List all organizations (super_admin dashboard: org dropdown + list)
  async listOrganizations() {
    const { data, error } = await supabase
      .from("organizations")
      .select("id, name, email, created_at")
      .order("name", { ascending: true });
    if (error) throw error;
    return data;
  },

  // List platform-scope admins (super_admin + org_admin — event_id NULL)
  // with their org name, for the super_admin dashboard.
  async listPlatformAdmins() {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*, organizations(name)")
      .is("event_id", null)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // Create a new organization (super_admin only, enforced by RLS in Pass 3 — for now any admin can call this)
  async createOrganization(name, email) {
    const { data, error } = await supabase
      .from("organizations")
      .insert({ name, email })
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// BILLING (super_admin only — schema + manually-set status, no
// real Stripe integration for Cocomo's own subscription revenue)
// ═══════════════════════════════════════════════════════════

export const billing = {
  // Org-scoped reads — used by the org_admin's own view (RLS restricts
  // these to the caller's own org regardless of the orgId passed in).
  async getSubscriptionForOrg(orgId) {
    const { data, error } = await supabase
      .from("org_subscriptions")
      .select("*, billing_plans(name, type, price, event_limit)")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    if (error) throw error;
    return data;
  },

  async listEventBillingForOrg(orgId) {
    const { data, error } = await supabase
      .from("event_billing")
      .select("*, events(name)")
      .eq("org_id", orgId)
      .order("status");
    if (error) throw error;
    return data;
  },

  async listPlans() {
    const { data, error } = await supabase
      .from("billing_plans")
      .select("*")
      .eq("active", true)
      .order("price");
    if (error) throw error;
    return data;
  },

  async listSubscriptions() {
    const { data, error } = await supabase
      .from("org_subscriptions")
      .select("*, organizations(name), billing_plans(name, type, price)")
      .order("current_period_end", { ascending: false, nullsFirst: true });
    if (error) throw error;
    return data;
  },

  async createSubscription(orgId, planId, status) {
    const { data, error } = await supabase
      .from("org_subscriptions")
      .insert({ org_id: orgId, plan_id: planId, status })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateSubscriptionStatus(id, status) {
    const { data, error } = await supabase
      .from("org_subscriptions")
      .update({ status })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async listEventBilling() {
    const { data, error } = await supabase
      .from("event_billing")
      .select("*, events(name), organizations(name)")
      .order("status");
    if (error) throw error;
    return data;
  },

  async createEventBilling(eventId, orgId, billingType, amount) {
    const { data, error } = await supabase
      .from("event_billing")
      .insert({ event_id: eventId, org_id: orgId, billing_type: billingType, amount: amount || null })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateEventBillingStatus(id, status) {
    const updates = { status };
    if (status === "paid") updates.paid_at = new Date().toISOString();
    const { data, error } = await supabase
      .from("event_billing")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};
