// src/services/api.js
// ─────────────────────────────────────────────────────────
// All Supabase CRUD operations organized by domain.
// Import into components: import { registrations, matches } from '@/services/api'
// ─────────────────────────────────────────────────────────

import { supabase } from "../supabaseClient";

// ═══════════════════════════════════════════════════════════
// EVENTS
// ═══════════════════════════════════════════════════════════

export const events = {
  async get(eventId) {
    const { data, error } = await supabase
      .from("events")
      .select("*, organizations(*), event_dates(*)")
      .eq("id", eventId)
      .single();
    if (error) throw error;
    return data;
  },

  async getByOrg(orgId) {
    const { data, error } = await supabase
      .from("events")
      .select("*")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async update(eventId, updates) {
    const { data, error } = await supabase
      .from("events")
      .update(updates)
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateFundraising(eventId, amount) {
    const { data, error } = await supabase
      .from("events")
      .update({ fundraising_current: amount })
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateRules(eventId, rulesContent) {
    const { data, error } = await supabase
      .from("events")
      .update({ rules_content: rulesContent })
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateStatus(eventId, status) {
    const updates = { status };
    if (status === "registration_open") updates.published_at = new Date().toISOString();
    const { data, error } = await supabase
      .from("events")
      .update(updates)
      .eq("id", eventId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// REGISTRATIONS
// ═══════════════════════════════════════════════════════════

export const registrations = {
  // Public: submit a new registration
  async create(eventId, formData) {
    const { data: event } = await supabase
      .from("events")
      .select("entry_fee, recon_prefix, recon_counter")
      .eq("id", eventId)
      .single();

    const { data, error } = await supabase
      .from("registrations")
      .insert({
        event_id: eventId,
        team_name: formData.teamName,
        team_slogan: formData.slogan || null,
        captain_name: formData.captainName,
        captain_email: formData.captainEmail,
        captain_phone: formData.captainPhone,
        captain_shirt: formData.captainShirt || null,
        captain_dietary: formData.captainDiet || null,
        payment_method: formData.paymentMethod,
        fee_amount: event.entry_fee,
        donation_amount: formData.donation || 0,
        total_amount: event.entry_fee + (formData.donation || 0),
        image_consent: formData.imageConsent || false,
        waiver_accepted: formData.waiverAccepted || false,
        team_story: formData.story || null,
        // reconciliation_code auto-generated by trigger
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: list all registrations for an event
  async list(eventId, filters = {}) {
    let query = supabase
      .from("registrations")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });

    if (filters.paymentStatus) query = query.eq("payment_status", filters.paymentStatus);
    if (filters.status) query = query.eq("status", filters.status);
    if (filters.search) {
      query = query.or(
        `team_name.ilike.%${filters.search}%,captain_name.ilike.%${filters.search}%,reconciliation_code.ilike.%${filters.search}%`
      );
    }

    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Admin: batch update registrations (payment confirmations, rejections)
  async batchUpdate(updates) {
    // updates = [{ id, payment_status, status, payment_confirmed_by, ... }]
    const promises = updates.map(({ id, ...fields }) =>
      supabase.from("registrations").update(fields).eq("id", id)
    );
    const results = await Promise.all(promises);
    const errors = results.filter((r) => r.error);
    if (errors.length) throw new Error(`${errors.length} updates failed`);
    return results.map((r) => r.data);
  },

  // Toggle payment status independently (checkbox-driven)
  async setPaymentReceived(id, received, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        payment_status: received ? "paid" : "pending",
        payment_confirmed_at: received ? new Date().toISOString() : null,
        payment_confirmed_by: received ? adminUserId : null,
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Toggle registration approval independently (checkbox-driven)
  async setApproved(id, approved, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        status: approved ? "approved" : "submitted",
        confirmed_at: approved ? new Date().toISOString() : null,
        approved_by: approved ? adminUserId : null,
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: confirm a single payment
  async confirmPayment(id, adminUserId) {
    const { data, error } = await supabase
      .from("registrations")
      .update({
        payment_status: "paid",
        status: "confirmed",
        payment_confirmed_at: new Date().toISOString(),
        payment_confirmed_by: adminUserId,
        confirmed_at: new Date().toISOString(),
      })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: reject registration
  async reject(id) {
    const { data, error } = await supabase
      .from("registrations")
      .update({ status: "rejected" })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// TEAMS
// ═══════════════════════════════════════════════════════════

export const teams = {
  // Create team from confirmed registration
  async createFromRegistration(registration) {
    const { data, error } = await supabase
      .from("teams")
      .insert({
        event_id: registration.event_id,
        registration_id: registration.id,
        name: registration.team_name,
        slogan: registration.team_slogan,
        logo_url: registration.team_logo_url,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async list(eventId) {
    const { data, error } = await supabase
      .from("teams")
      .select("*, players(*), pool:pools(name)")
      .eq("event_id", eventId)
      .order("name");
    if (error) throw error;
    return data;
  },

  async checkIn(teamId, adminUserId) {
    const { data, error } = await supabase
      .from("teams")
      .update({
        checked_in: true,
        checked_in_at: new Date().toISOString(),
        checked_in_by: adminUserId,
      })
      .eq("id", teamId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async undoCheckIn(teamId) {
    const { data, error } = await supabase
      .from("teams")
      .update({ checked_in: false, checked_in_at: null, checked_in_by: null })
      .eq("id", teamId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async assignPool(teamId, poolId) {
    const { data, error } = await supabase
      .from("teams")
      .update({ pool_id: poolId })
      .eq("id", teamId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async markEliminated(teamId, finalRank) {
    const { data, error } = await supabase
      .from("teams")
      .update({ eliminated: true, final_rank: finalRank })
      .eq("id", teamId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// PLAYERS
// ═══════════════════════════════════════════════════════════

export const players = {
  async createBatch(teamId, eventId, playerList) {
    // playerList = [{ name, email, phone, is_captain, shirt_size, dietary_needs, sort_order }]
    const rows = playerList.map((p) => ({
      team_id: teamId,
      event_id: eventId,
      full_name: p.name,
      email: p.email || null,
      phone: p.phone || null,
      is_captain: p.is_captain || false,
      shirt_size: p.shirt_size || null,
      dietary_needs: p.dietary_needs || null,
      sort_order: p.sort_order || 0,
    }));
    const { data, error } = await supabase.from("players").insert(rows).select();
    if (error) throw error;
    return data;
  },

  async getByPhone(eventId, phone) {
    const { data, error } = await supabase
      .from("players")
      .select("*, team:teams(*)")
      .eq("event_id", eventId)
      .eq("phone", phone)
      .eq("is_captain", true)
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// MATCHES
// ═══════════════════════════════════════════════════════════

export const matches = {
  async list(eventId, filters = {}) {
    let query = supabase
      .from("matches")
      .select(
        "*, team_a:teams!matches_team_a_id_fkey(id, name), team_b:teams!matches_team_b_id_fkey(id, name), playing_area:playing_areas(number, name), pool:pools(name), bracket:brackets(name)"
      )
      .eq("event_id", eventId)
      .order("round")
      .order("match_number");

    if (filters.status) query = query.eq("status", filters.status);
    if (filters.poolId) query = query.eq("pool_id", filters.poolId);
    if (filters.bracketId) query = query.eq("bracket_id", filters.bracketId);

    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  async getLive(eventId) {
    const { data, error } = await supabase
      .from("matches")
      .select(
        "*, team_a:teams!matches_team_a_id_fkey(id, name), team_b:teams!matches_team_b_id_fkey(id, name), playing_area:playing_areas(number, name)"
      )
      .eq("event_id", eventId)
      .in("status", ["live", "score_entered", "disputed"])
      .order("playing_area_id");
    if (error) throw error;
    return data;
  },

  // Captain: submit score (home captain only)
  async submitScore(matchId, teamAScore, teamBScore, captainPhone) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        team_a_score: teamAScore,
        team_b_score: teamBScore,
        score_entered_at: new Date().toISOString(),
        score_entered_by: captainPhone,
        status: "score_entered",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Captain: verify score (away captain)
  async verifyScore(matchId) {
    const { data: match } = await supabase
      .from("matches")
      .select("team_a_score, team_b_score, team_a_id, team_b_id")
      .eq("id", matchId)
      .single();

    const winnerId =
      match.team_a_score > match.team_b_score ? match.team_a_id : match.team_b_id;
    const loserId =
      match.team_a_score > match.team_b_score ? match.team_b_id : match.team_a_id;

    const { data, error } = await supabase
      .from("matches")
      .update({
        score_verified: true,
        score_verified_at: new Date().toISOString(),
        winner_id: winnerId,
        loser_id: loserId,
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Captain: dispute score
  async disputeScore(matchId, reason) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        score_disputed: true,
        dispute_reason: reason,
        status: "disputed",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin/Referee: resolve dispute
  async resolveDispute(matchId, finalScoreA, finalScoreB, resolvedBy) {
    const { data: match } = await supabase
      .from("matches")
      .select("team_a_id, team_b_id")
      .eq("id", matchId)
      .single();

    const winnerId =
      finalScoreA > finalScoreB ? match.team_a_id : match.team_b_id;
    const loserId =
      finalScoreA > finalScoreB ? match.team_b_id : match.team_a_id;

    const { data, error } = await supabase
      .from("matches")
      .update({
        team_a_score: finalScoreA,
        team_b_score: finalScoreB,
        winner_id: winnerId,
        loser_id: loserId,
        score_verified: true,
        score_disputed: false,
        dispute_resolved_by: resolvedBy,
        dispute_resolved_at: new Date().toISOString(),
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: force verify (skip away captain confirmation)
  async forceVerify(matchId, adminUserId) {
    return this.resolveDispute(
      matchId,
      null, // keep existing scores
      null,
      adminUserId
    );
  },

  // Admin: assign to playing area
  async assignArea(matchId, playingAreaId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        playing_area_id: playingAreaId,
        status: "ready",
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: start match
  async startMatch(matchId) {
    // Randomize home captain
    await supabase.rpc("assign_home_captain", { match_uuid: matchId });
    const { data, error } = await supabase
      .from("matches")
      .update({
        status: "live",
        started_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: award bye (no-show opponent)
  async awardBye(matchId, winnerTeamId, loserTeamId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        winner_id: winnerTeamId,
        loser_id: loserTeamId,
        team_a_score: 0,
        team_b_score: 0,
        score_verified: true,
        status: "completed",
        completed_at: new Date().toISOString(),
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: reassign home captain
  async reassignHomeCaptain(matchId, newHomeCaptainTeamId, newAwayCaptainTeamId) {
    const { data, error } = await supabase
      .from("matches")
      .update({
        home_captain_team_id: newHomeCaptainTeamId,
        away_captain_team_id: newAwayCaptainTeamId,
      })
      .eq("id", matchId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// POOLS & STANDINGS
// ═══════════════════════════════════════════════════════════

export const pools = {
  async create(eventId, poolNames) {
    const rows = poolNames.map((name, i) => ({
      event_id: eventId,
      name,
      sort_order: i,
    }));
    const { data, error } = await supabase.from("pools").insert(rows).select();
    if (error) throw error;
    return data;
  },

  async listWithStandings(eventId) {
    const { data, error } = await supabase
      .from("pools")
      .select("*, pool_standings(*, team:teams(id, name, slogan))")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    // Sort standings by rank within each pool
    return data.map((pool) => ({
      ...pool,
      pool_standings: pool.pool_standings.sort((a, b) => (a.pool_rank || 99) - (b.pool_rank || 99)),
    }));
  },
};

// ═══════════════════════════════════════════════════════════
// PLAYING AREAS
// ═══════════════════════════════════════════════════════════

export const playingAreas = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("playing_areas")
      .select("*")
      .eq("event_id", eventId)
      .order("number");
    if (error) throw error;
    return data;
  },

  async updateStatus(areaId, status) {
    const { data, error } = await supabase
      .from("playing_areas")
      .update({ status })
      .eq("id", areaId)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async createBatch(eventId, count, label = "Court") {
    const rows = Array.from({ length: count }, (_, i) => ({
      event_id: eventId,
      number: i + 1,
      name: `${label} ${i + 1}`,
      status: "available",
    }));
    const { data, error } = await supabase.from("playing_areas").insert(rows).select();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// BRACKETS
// ═══════════════════════════════════════════════════════════

export const brackets = {
  async create(eventId, name, bracketType, format) {
    const { data, error } = await supabase
      .from("brackets")
      .insert({ event_id: eventId, name, bracket_type: bracketType, format })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async listWithMatches(eventId) {
    const { data, error } = await supabase
      .from("brackets")
      .select("*, matches(*, team_a:teams!matches_team_a_id_fkey(name), team_b:teams!matches_team_b_id_fkey(name))")
      .eq("event_id", eventId);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// VOLUNTEERS
// ═══════════════════════════════════════════════════════════

export const volunteers = {
  // Public: submit application
  async apply(eventId, formData) {
    const { data, error } = await supabase
      .from("volunteer_applications")
      .insert({
        event_id: eventId,
        primary_role_id: formData.primaryRoleId,
        other_role_ids: formData.otherRoleIds || [],
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.phone || null,
        experience: formData.experience || null,
        certifications: formData.certifications || null,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // Admin: list applications
  async list(eventId, filters = {}) {
    let query = supabase
      .from("volunteer_applications")
      .select("*, primary_role:volunteer_roles!volunteer_applications_primary_role_id_fkey(title)")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false });
    if (filters.status) query = query.eq("status", filters.status);
    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Admin: batch approve/decline
  async batchUpdate(updates) {
    const promises = updates.map(({ id, status, assignedRoleId, approvedBy }) =>
      supabase.from("volunteer_applications").update({
        status,
        assigned_role_id: assignedRoleId || null,
        approved_by: approvedBy || null,
        approved_at: status === "approved" ? new Date().toISOString() : null,
      }).eq("id", id)
    );
    const results = await Promise.all(promises);
    const errors = results.filter((r) => r.error);
    if (errors.length) throw new Error(`${errors.length} updates failed`);
    return results;
  },

  // Roles
  async listRoles(eventId) {
    const { data, error } = await supabase
      .from("volunteer_roles")
      .select("*")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// SPONSORS
// ═══════════════════════════════════════════════════════════

export const sponsors = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("sponsors")
      .select("*, tier:sponsor_tiers(name, amount, sort_order)")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },

  async listTiers(eventId) {
    const { data, error } = await supabase
      .from("sponsor_tiers")
      .select("*, sponsors(*)")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },

  async create(eventId, sponsorData) {
    const { data, error } = await supabase
      .from("sponsors")
      .insert({ event_id: eventId, ...sponsorData })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async update(id, updates) {
    const { data, error } = await supabase
      .from("sponsors")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ARTIFACTS
// ═══════════════════════════════════════════════════════════

export const artifacts = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("artifacts")
      .select("*")
      .eq("event_id", eventId)
      .order("artifact_type");
    if (error) throw error;
    return data;
  },

  async updateStatus(id, status, userId) {
    const updates = { status };
    if (status === "review") {
      updates.reviewed_by = userId;
      updates.reviewed_at = new Date().toISOString();
    } else if (status === "approved") {
      updates.approved_by = userId;
      updates.approved_at = new Date().toISOString();
    } else if (status === "published") {
      updates.published_by = userId;
      updates.published_at = new Date().toISOString();
    }
    const { data, error } = await supabase
      .from("artifacts")
      .update(updates)
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async updateContent(id, content) {
    const { data, error } = await supabase
      .from("artifacts")
      .update({ content, version: supabase.rpc("increment_version", { artifact_id: id }) })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ANNOUNCEMENTS
// ═══════════════════════════════════════════════════════════

export const announcements = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("announcements")
      .select("*")
      .eq("event_id", eventId)
      .eq("active", true)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  async create(eventId, message, options = {}) {
    const { data, error } = await supabase
      .from("announcements")
      .insert({
        event_id: eventId,
        message,
        priority: options.priority || "normal",
        show_on_tv: options.showOnTV !== false,
        created_by: options.createdBy || null,
        expires_at: options.expiresAt || null,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  async deactivate(id) {
    const { data, error } = await supabase
      .from("announcements")
      .update({ active: false })
      .eq("id", id);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// OTP AUTH (Captain Portal)
// ═══════════════════════════════════════════════════════════

export const otp = {
  // Request OTP — calls serverless function which sends SMS via Twilio
  async request(eventId, phone) {
    const response = await fetch("/api/send-otp", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ eventId, phone }),
    });
    if (!response.ok) throw new Error("Failed to send OTP");
    return response.json(); // { success: true, sessionId }
  },

  // Verify OTP code
  async verify(sessionId, code) {
    const { data, error } = await supabase
      .from("otp_sessions")
      .select("*, player:players(*, team:teams(*))")
      .eq("id", sessionId)
      .eq("otp_code", code)
      .gt("expires_at", new Date().toISOString())
      .single();

    if (error || !data) throw new Error("Invalid or expired code");

    // Mark as verified
    await supabase
      .from("otp_sessions")
      .update({ verified: true, verified_at: new Date().toISOString() })
      .eq("id", sessionId);

    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ACTIVITY LOG
// ═══════════════════════════════════════════════════════════

export const activityLog = {
  async log(eventId, action, entityType, entityId, details = {}, userId = null) {
    const { error } = await supabase.from("activity_log").insert({
      event_id: eventId,
      user_id: userId,
      action,
      entity_type: entityType,
      entity_id: String(entityId),
      details,
    });
    if (error) console.error("Activity log failed:", error);
  },

  async list(eventId, limit = 50) {
    const { data, error } = await supabase
      .from("activity_log")
      .select("*")
      .eq("event_id", eventId)
      .order("created_at", { ascending: false })
      .limit(limit);
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// GIFT BASKET & LOCAL SERVICES
// ═══════════════════════════════════════════════════════════

export const giftBasket = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("gift_basket_items")
      .select("*")
      .eq("event_id", eventId)
      .eq("active", true)
      .order("sort_order");
    if (error) throw error;
    return data;
  },
};

export const localServices = {
  async list(eventId) {
    const { data, error } = await supabase
      .from("local_services")
      .select("*")
      .eq("event_id", eventId)
      .order("sort_order");
    if (error) throw error;
    return data;
  },
};

// ═══════════════════════════════════════════════════════════
// ADMIN / AUTH
// ═══════════════════════════════════════════════════════════

export const admin = {
  // Get the admin_users row for the currently logged-in user
  async getCurrentAdmin() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;
    const { data, error } = await supabase
      .from("admin_users")
      .select("*, organizations(name), events(name)")
      .eq("id", user.id)
      .single();
    if (error) {
      // No matching admin_users row (e.g. invite wasn't processed yet, or not an admin)
      console.error("getCurrentAdmin failed:", error);
      return null;
    }
    return data;
  },

  // Create an invite (org_admin or super_admin)
  async createInvite(email, role, { orgId = null, eventId = null, displayName = null, invitedBy } = {}) {
    const { data, error } = await supabase
      .from("invites")
      .insert({
        email,
        role,
        org_id: orgId,
        event_id: eventId,
        display_name: displayName,
        invited_by: invitedBy,
      })
      .select()
      .single();
    if (error) throw error;
    return data;
  },

  // List pending (unused) invites, optionally scoped to an org
  async listInvites(orgId = null) {
    let query = supabase
      .from("invites")
      .select("*")
      .is("used_at", null)
      .gt("expires_at", new Date().toISOString())
      .order("created_at", { ascending: false });
    if (orgId) query = query.eq("org_id", orgId);
    const { data, error } = await query;
    if (error) throw error;
    return data;
  },

  // Fetch an invite by token (for the Accept Invite page, pre-signup)
  async getInviteByToken(token) {
    const { data, error } = await supabase
      .from("invites")
      .select("*, organizations(name)")
      .eq("token", token)
      .is("used_at", null)
      .gt("expires_at", new Date().toISOString())
      .single();
    if (error) throw error;
    return data;
  },

  // List admin_users for an org (Team panel)
  async listOrgAdmins(orgId) {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*")
      .eq("org_id", orgId)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // List the team relevant to one event: this org's org-level admins
  // (event_id NULL) plus admins scoped to this specific event.
  async listEventTeam(orgId, eventId) {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*")
      .eq("org_id", orgId)
      .or(`event_id.eq.${eventId},event_id.is.null`)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // List all organizations (super_admin dashboard: org dropdown + list)
  async listOrganizations() {
    const { data, error } = await supabase
      .from("organizations")
      .select("id, name, email, created_at")
      .order("name", { ascending: true });
    if (error) throw error;
    return data;
  },

  // List platform-scope admins (super_admin + org_admin — event_id NULL)
  // with their org name, for the super_admin dashboard.
  async listPlatformAdmins() {
    const { data, error } = await supabase
      .from("admin_users")
      .select("*, organizations(name)")
      .is("event_id", null)
      .order("created_at", { ascending: false });
    if (error) throw error;
    return data;
  },

  // Create a new organization (super_admin only, enforced by RLS in Pass 3 — for now any admin can call this)
  async createOrganization(name, email) {
    const { data, error } = await supabase
      .from("organizations")
      .insert({ name, email })
      .select()
      .single();
    if (error) throw error;
    return data;
  },
};
